### ISSUE TITLE
Symfony 3 : error of path to load codesnippet

### ISSUE THREAD

**Issue by falexis77** [egeloen/IvoryCKEditorBundle#261] opened 2016-11-16 13:37 UTC
Hi,
i have a problem, i download ivoryckeditor and add a plugin codesnippet with dependencies.
I have included the folder ckeditor/plugins in the resource folder of my bundle back

config.yml
```
ivory_ck_editor:
    default_config: blog
    configs:
        blog:
            uiColor:      "#FCFCFC"
            toolbar:      [ [ 'Preview','-', 'CodeSnippet' ], [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ], [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ], [ 'Source' ], [ "About" ], "/", [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript','-','RemoveFormat' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink','Anchor' ], [ 'pbckcode', 'Image', 'Video', 'Table','SpecialChar','Iframe' ], '/', [ 'Styles', 'Format','Font','FontSize' ], [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
            extraPlugins: "codesnippet,clipboard,dialog,lineutils,widget,dialogui"
    plugins:
        codesnippet:
            path:     "/bundles/back/ckeditor/plugins/codesnippet/"
            filename: "plugin.js"
        clipboard:
            path:     "/bundles/back/ckeditor/plugins/clipboard/"
            filename: "plugin.js"
        dialog:
            path:     "/bundles/back/ckeditor/plugins/dialog/"
            filename: "plugin.js"
        lineutils:
            path:     "/bundles/back/ckeditor/plugins/lineutils/"
            filename: "plugin.js"
        widget:
            path:     "/bundles/back/ckeditor/plugins/widget/"
            filename: "plugin.js"
        dialogui:
            path:     "/bundles/back/ckeditor/plugins/dialogui/"
            filename: "plugin.js"
```

but on admin, a error appear on console : NetworkError: 404 Not Found - http://site.fr/bundles/ivoryckeditor/plugins/codesnippet/plugin.js
I precise a path for the sources but it continue to search in ivory file!

**Comment by egeloen** [comment] 2016-11-16 17:52
Hum, this is weird. I just give a try to this branch: https://github.com/symfony/symfony-standard/compare/master...egeloen:ckeditor-plugin which is mostly the same as your code and it's working. Are you sure you have clear your cache as well as install assets in the web directory on the good path?

**Comment by egeloen** [comment] 2016-11-20 09:05
@falexis77 Any news?

**Comment by Titou74** [comment] 2016-11-21 20:32
Hello,

I made a little modification to add a skin to ivoryckeditor. Perhaps you have to make the same for plugins.
- I put the skin on "<myBundle>/lib/ckeditor/skins/moono-lisa/" and I install the assets
- On the configuration, I put : skin: "moono-lisa,../<myBundle>/lib/ckeditor/skins/moono-lisa/"

So, try to replace "/bundles/back/" with "../back/"

**Comment by egeloen** [comment] 2016-11-22 09:40
@Titou74 If you need to do this "hack", there is somethign wrong somewhere... Can you open an dedicated issue since it is not the same topic please?

**Comment by egeloen** [comment] 2017-01-12 01:01
Closing as the original bug is not reproductible.

**Closed by egeloen** 2017-01-12 01:01 UTC
