### ISSUE TITLE
DEPRECATED Symfony 3.2

### ISSUE THREAD

**Issue by botjaeger** [egeloen/IvoryCKEditorBundle#349] opened 2018-05-30 01:01 UTC
`User Deprecated: The "assets.packages" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

**AND**

`User Deprecated: The "ivory_ck_editor.renderer.json_builder" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

I'm currently using Symfony 3.4 and planning on migrating to Symfony 4 but I found this log message on _Deprecations_ section.

Hope you guys can fix this. Thank you.

**Comment by thelem** [comment] 2018-09-23 17:02
Duplicate of #329 

This bundle isn't being actively developed. It has been forked by FOS, see https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/1.x/docs/migration.rst for migration instructions.

**Closed as completed** 2019-02-20 08:00 UTC
