### ISSUE TITLE
The bundle is incompatible with Symfony4

### ISSUE THREAD

**Issue by alyamovsky** [egeloen/IvoryCKEditorBundle#343] opened 2018-01-31 10:30 UTC
Hi there! Due to upper version bounds for such dependencies as symfony/framework-bundle, symfony/dependency-injection, twig etc. the bundle is currently incompatible with Symfony4 projects. Are you planning to update it?

**Comment by szymach** [comment] 2018-02-05 10:50
Duplicate of #329

**Comment by pulzarraider** [comment] 2019-01-23 13:33
See https://symfony.com/blog/finding-a-new-home-for-ivoryckeditorbundle

**Comment by mverijdt** [comment] 2019-08-06 15:11
the new home was found: [Friends Of Symfony - CK Editor Bundle](https://github.com/FriendsOfSymfony/FOSCKEditorBundle)

It is compatible now, this issue can be closed

**Closed as completed** 2024-07-04 19:48 UTC
