### ISSUE TITLE
Required field not rendered

### ISSUE THREAD

**Issue by flim** [egeloen/IvoryCKEditorBundle#305] opened 2017-07-07 19:46 UTC
Im using
**Symfony 3.3**
**IvoryCKEditorBundle 4.0.6**

And my field
    
    ->add('description', CKEditorType::class, ['required' => true]);

doesn't render as required for the html validation.

Even if I add on the twig as

    {{ form_widget(form.description, {'required': 'required'}) }}

It is a version issue ?

Thanks

PS: a similar issue exists #148

**Comment by egeloen** [comment] 2017-07-11 13:31
Hum, a long time ago, I have fixed it with a8a9a7e in the 2.1.6 version of the bundle. Can you check if the required flag is rendered on your textarea?

**Comment by flim** [comment] 2017-07-11 13:48
Thanks for coming back here :) 
I already checked, there is no required attribute on the html.
The current CKEditorType doesn't looks the same as your commit.

**Comment by Muspi** [comment] 2017-07-12 11:32
Hello, I have the same problem here, required is not rendered.

Im using
Symfony 3.3
IvoryCKEditorBundle master

Thanks

**Comment by egeloen** [comment] 2017-07-12 17:08
So, I just give a try to your issue and the `required` attr is rendered on the textarea when you take a look to the page source but then CKEditor removes it dynamically... 

IMO this behavior should be reported to the CKEditor team as the bundle does the right thing whereas CKEditor seems removing the attr and don't take it into account.

**Comment by Muspi** [comment] 2017-07-12 17:22
Problem here, and solved in net releases?

https://dev.ckeditor.com/ticket/8031

**Comment by egeloen** [comment] 2017-07-13 08:58
Can someone open an issue on the CKEditor bugtracker as it looks like a regression to me?

**Comment by egeloen** [comment] 2017-07-14 16:14
Closing as the bundle renders the appropriate html 5 attribute.

**Closed by egeloen** 2017-07-14 16:14 UTC

**Comment by imajim** [comment] 2020-06-18 08:45
you can add a constraint to form builder:
```
$builder->add('description', CKEditorType::class, [
            'label' => 'Description',
            'config' => ['toolbar' => 'basic'],
            'required' => true,
            'constraints'=>[
                new NotBlank(),
            ]
        ])
```
