### ISSUE TITLE
var CKEDITOR_BASEPATH

### ISSUE THREAD

**Issue by xorgxx** [egeloen/IvoryCKEditorBundle#167] opened 2015-04-21 05:46 UTC
hi
i just install ckeditorbundle with elfinder and i get this error : 
```
TypeError: $ is not a function
var CKEDITOR_BASEPATH = "/bundles/ivoryckeditor/";
```
but i get this error only on ajax call, if i call normal way meaning php i get no probleme.
if i dont set elfinder again no probleme.
symfony 2.6.6, ckeditor 3.0.1, elfinder 5.0.4, js 1.11.1
thanks to help.

**Comment by egeloen** [comment] 2015-04-21 18:55
I don't really understand the issue. You're talking about `$ is not a function` but there is no usage of JQuery in the project at all. Futhermore, the line `var CKEDITOR_BASEPATH = "/bundles/ivoryckeditor/";` can't trigger the error since there is no `$` in this line.

**Comment by egeloen** [comment] 2015-08-14 08:33
Closing as there is no feedback and as explain in the previous comment, the issue is not related to the bundle.

**Closed by egeloen** 2015-08-14 08:33 UTC
