### ISSUE TITLE
extraAllowedContent !

### ISSUE THREAD

**Issue by xorgxx** [egeloen/IvoryCKEditorBundle#215] opened 2016-02-24 13:31 UTC
hi i try to add in ckeditor ```span``` balise, but it das not allow me.

here is my config.yml

```
`ivory_ck_editor:
    default_config:                     my_custom_config    # Utiliser par defaut la configuration my_custom_config
    configs:
        my_custom_config:
            filebrowserBrowseRoute:     elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor
            language:                   %locale%
            toolbar:                    standard            # Charger la toolbar tollbar_1 (voir plus bas)
            stylesSet:                  my_styles           # Chargement des styles personnalisables my_styles (voir plus bas)
            uiColor:                    "#FCFCFC"           # Couleur de fond de l'interface
            height:                     '600px'             # Hauteur par défaut
            # Utiliser les styles css suivants dans le contenu de l'éditeur. Permet de voir le rendu en temps réeem
            contentsCss:                ['css/master.css']
            allowedContent:             true
            extraAllowedContent :       ['span body head footer container i *(*) *{*}']
    styles:         # Configuration des styles personnalisables
        my_styles:
            - { name: "Alerte Success", element: "div",  attributes: { class: "alert alert-success", role: "alert" }}
            - { name: "Alerte Info", element: "div",  attributes: { class: "alert alert-info", role: "alert" }}
            - { name: "Alerte Warning", element: "div",  attributes: { class: "alert alert-warning", role: "alert" }}
            - { name: "Alerte Danger", element: "div",  attributes: { class: "alert alert-danger", role: "alert" }}
            - { name: "Badge", element: "span",  attributes: { class: "badge" }}
```
in the text it delete automate all ```<span> and <i> ``` balise.

thank for your help.

**Comment by egeloen** [comment] 2016-02-24 13:39
That's strange as it works for me with your config... What did you mean exactly by it does not work? 

To try to reproduce, I have entered some text in the editor, then I go to the source and add a span tag. Then I go back to the editor, add some more text and go back to source, then at this state, the span tag is still here (no alteration).

**Comment by xorgxx** [comment] 2016-02-24 14:19
```
<div class="container text-center">
    <h1 style="visibility: visible; animation-name: fadeInUp;" ng-model="test" class="wow fadeInUp">Whatever you feel</h1>
    <div class="col-sm-8 col-sm-offset-2">
        <h3 style="visibility: visible; animation-name: fadeInUp;" class="concrete wow fadeInUp">
              with just a few clicks.
        </h3>
        <div>
            <h5 style="visibility: visible; animation-name: fadeInUp;" class="top20 wow fadeInUp">You'll
                <span class="fa fa-heart pomegranate"></span>
                    neonatis MultiPurpose Template
            </h5>
        </div>
    </div>
</div>
```
when i edite as "ckeditor" das take of ``` <span class="fa fa-heart pomegranate"></span> ```

**Comment by xorgxx** [comment] 2016-02-24 14:26
it give this 

```
<div class="container text-center">
<h1 class="wow fadeInUp" ng-model="test">Whatever your feel</h1>

<div class="col-sm-8 col-sm-offset-2">
<h3 class="concrete wow fadeInUp">with just a few clicks.</h3>

<div>
<h5 class="top20 wow fadeInUp">You&#39;ll MultiPurpose Template</h5>
</div>
</div>
</div>

```

**Comment by xorgxx** [comment] 2016-02-24 14:35
so i have just make test AND the "bug" is that the ```<span class="fa fa-heart pomegranate"></span> ``` have no text value, if i put text value then not probleme !!

**Comment by egeloen** [comment] 2016-02-24 17:25
Have you tried to use the following:

``` javascript
protectedSource: [ "/<span[^>]*><\/span>/g" ]
```

**Comment by xorgxx** [comment] 2016-02-24 18:09
same ....

**Comment by egeloen** [comment] 2016-02-25 08:27
I'm sorry but it is related to CKEditor and not the bundle itself (no bug in it)... I'm not a CKEditor expert at all and so, I can't help more.

As the issue is not related to the bundle, I close it and you should ask support elsewhere (stackoverflow, IRC, ...) as I can't do much more for you... If you find a solution, please report it here for others :)

**Closed by egeloen** 2016-02-25 08:27 UTC

**Comment by xorgxx** [comment] 2016-04-10 19:50
it since that this problem can be stop by ```CKEDITOR.dtd.$removeEmpty.span = 0;``` but here to set ?

**Comment by xorgxx** [comment] 2016-04-10 20:23
i just add this in my header html ```<script>CKEDITOR.dtd.$removeEmpty['span'] = false;</script>``` and it work !!

**Comment by egeloen** [comment] 2016-04-12 14:04
@xorgxx I have added a new section in the doc explaining how you should append your code.
