### ISSUE TITLE
Attribute required doesn't work

### ISSUE THREAD

**Issue by davidskaraboo** [egeloen/IvoryCKEditorBundle#309] opened 2017-07-27 11:24 UTC
Hi mates!
I am adding the required attribute in form type but doesn't appear in the textarea.... some solution?

Symfony 3.4

The code:
```
'content' => [
                        'required' => true,
                        'field_type' => CKEditorType::class,
                        'config' => array(
                            'toolbar' => 'default'
                        )
               ],
```

**Comment by egeloen** [comment] 2017-07-31 14:53
Duplicate of #305 

To resume, it seems there is a bug in CKEditor as the bundle renders the HTML5 required attribute and then, CKEditor removes it from the DOM and don't do anything with it...

**Closed by egeloen** 2017-07-31 14:53 UTC

**Comment by imajim** [comment] 2020-06-18 08:45
you can add a constraint to form builder:
```
$builder->add('description', CKEditorType::class, [
            'label' => 'Description',
            'config' => ['toolbar' => 'basic'],
            'required' => true,
            'constraints'=>[
                new NotBlank(),
            ]
        ])
```
