### ISSUE TITLE
Attr class removed by CKeditor

### ISSUE THREAD

**Issue by jbracoupeau** [egeloen/IvoryCKEditorBundle#252] opened 2016-09-19 15:05 UTC
Hey guys, I have a problem, CKEditor removes attr "class" from the content, even if I added allowedContent: true in my config.  All the rest of my config works fine, any idea ?

When I past code with classes, it saves it in my db with the classes, but if I want to edit the code, then classes are gone :/

# CKEditor
```
ivory_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Maximize", "-", "Source", "-", "Save"], .....]
            uiColor: "#FFFFFF"
            allowedContent: true
```

**Comment by egeloen** [comment] 2016-09-19 17:10
AFAIR, `allowContext` is not enought in order to keep everything as entered in the editor... There is something called `ACF` for (Advenced Content Filter) which maybe is the root cause of your issue...

Unfortunatelly, this is all I know related to your issue, so, I can't help more...

**Comment by egeloen** [comment] 2016-09-22 18:56
@jbracoupeau Does it help you?

**Comment by jbracoupeau** [comment] 2016-09-26 07:28
Hi,

not really, I chose to do it another way, not using class attributes within the texts in CKEditor ;)

Thanks anyway, have a great week

**Comment by egeloen** [comment] 2016-09-26 13:38
Ok, so let's close it as there is nothing wrong in the bundle :)

**Closed by egeloen** 2016-09-26 13:38 UTC

**Comment by mssimi** [comment] 2017-04-10 05:27
Its not allowContent but allowedContent
